---
# Certificates generation
- hosts: Wazuh-single
  roles:
    - role: ../roles/wazuh/wazuh-indexer
      perform_installation: false
  become: false
  vars:
    indexer_node_master: true
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: 127.0.0.1
        role: indexer
  tags:
    - generate-certs
# Single node
- hosts: Wazuh-single
  become: true
  become_user: root
  roles:
    - role: ../roles/wazuh/wazuh-indexer
    - role: ../roles/wazuh/ansible-wazuh-manager
    - role: ../roles/wazuh/ansible-filebeat-oss
    - role: ../roles/wazuh/wazuh-dashboard
  vars_files:
    - ./vars/vars-development.yml
    - ./vars/secrets-development.yml
  vars:  # see https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/reference.html
    single_node: true
    minimum_master_nodes: 1
    indexer_node_master: true
    indexer_network_host: 127.0.0.1
    filebeat_node_name: node-1
    filebeat_output_indexer_hosts:
      - 127.0.0.1
    instances:
      node1:
        name: node-1       # Important: must be equal to indexer_node_name.
        ip: 127.0.0.1
        role: indexer
    ansible_shell_allow_world_readable_temp: true

    wazuh_manager_api:
      bind_addr: 0.0.0.0
      port: 55000
      https: yes
      https_key: "server.key"
      https_cert: "server.crt"
      https_use_ca: False
      https_ca: "ca.crt"
      logging_level: "info"
      cors: no
      cors_source_route: "*"
      cors_expose_headers: "*"
      cors_allow_headers: "*"
      cors_allow_credentials: no
      cache: yes
      cache_time: 0.750
      access_max_login_attempts: 5
      access_block_time: 300
      access_max_request_per_minute: 300
      drop_privileges: yes
      experimental_features: no

    wazuh_manager_integrations:
      - name: VirusTotal
        api_key: "{{ virustotal_api_key }}"
        rule_id: 100200,100201
        alert_format: 'json'

    wazuh_manager_vulnerability_detector:
      enabled: 'yes'
      interval: '5m'
      min_full_scan_interval: '6h'
      run_on_start: 'yes'
      providers:
        - enabled: 'yes'
          os:
            - 'trusty'
            - 'xenial'
            - 'bionic'
            - 'jammy'
          update_interval: '1h'
          name: '"canonical"'
        - enabled: 'no'
          os:
            - 'wheezy'
            - 'stretch'
            - 'jessie'
            - 'buster'
          update_interval: '1h'
          name: '"debian"'
        - enabled: 'no'
          update_from_year: '2010'
          update_interval: '1h'
          name: '"redhat"'
        - enabled: 'yes'
          update_from_year: '2010'
          update_interval: '1h'
          name: '"nvd"'

    wazuh_manager_sca:
      enabled: 'yes'
      scan_on_start: 'yes'
      interval: '12h'
      skip_nfs: 'yes'
      day: ''
      wday: ''
      time: ''

    wazuh_manager_syscollector:
      disable: 'no'
      interval: '1h'
      scan_on_start: 'yes'
      hardware: 'yes'
      os: 'yes'
      network: 'yes'
      packages: 'yes'
      ports_no: 'yes'
      processes: 'yes'
